server:
  port: 8081

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/msinventario}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

# URL de MSProductos (para RestTemplate)
msproductos:
  url: ${MSPRODUCTOS_URL:http://localhost:8080}

ms:
  api:
    key: ${MS_API_KEY:}
